server:
  port: 8081
  servlet:
    context-path: /rest-auth

guavapay:
  app:
    jwtExpirationMs: '86400000'
    jwtSecret: mySecretKey
spring:
  datasource:
    username: XXXX
    url: jdbc:postgresql://XXXX
    password: XXXX
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: guavapay_test
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update

